
title: My Resume
url: 'http://williamow.com'
baseurl: "" #change it according to your repository name



# Profile information
yourname: William Ow  ## put your name
title: 'Cyber Security Professional &amp; Programme Manager'  ## your title
location: Singapore , SG


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
instagram: http://www.instagram.com  ## your instagram account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.youtube.com  ## your youtube account url
google: http://maps.google.com  ## your google map account url



# Update all the sections by editing the files inside _includes folder.
